const fs = require('fs');
try {
  const categories = ['accessories', 'cat-needs', 'diverse', 'dog-needs', 'pet-grooming'];
  const templates = {
    'accessories': [
      { title: "Stainless Steel Pet Bowl", weight: "1 pc", term: "pet dog bowl" },
      { title: "Sturdy Dog Leash", weight: "1 pc", term: "dog leash" },
      { title: "Pet Training Pads", weight: "30 pcs", term: "pet training pads" },
      { title: "Squeaky Chew Toy", weight: "1 pc", term: "dog toy" },
      { title: "Adjustable Pet Collar", weight: "1 pc", term: "pet collar" },
      { title: "Pet Carrier Bag", weight: "1 pc", term: "pet carrier" },
      { title: "Automatic Water Dispenser", weight: "1 pc", term: "pet water dispenser" },
      { title: "Reflective Harness", weight: "1 pc", term: "dog harness" },
      { title: "Pet Bed (Medium)", weight: "1 pc", term: "pet bed" },
      { title: "Poop Bag Dispenser", weight: "1 pc", term: "poop bag holder" },
      { title: "Compostable Poop Bags", weight: "60 pcs", term: "dog poop bags" },
      { title: "Catnip Toy", weight: "1 pc", term: "catnip toy" },
      { title: "Feather Wand Cat Toy", weight: "1 pc", term: "cat feather toy" },
      { title: "Interactive Puzzle Toy", weight: "1 pc", term: "dog puzzle toy" },
      { title: "Pet Car Seat Cover", weight: "1 pc", term: "pet car seat cover" },
      { title: "Rope Tug Toy", weight: "1 pc", term: "dog rope toy" },
      { title: "Ceramic Cat Bowl", weight: "1 pc", term: "cat bowl" },
      { title: "Slow Feeder Bowl", weight: "1 pc", term: "slow feeder dog bowl" },
      { title: "LED Dog Collar", weight: "1 pc", term: "led dog collar" },
      { title: "Pet Travel Bottle", weight: "1 pc", term: "dog travel water bottle" },
      { title: "Cat Tunnel", weight: "1 pc", term: "cat tunnel" },
      { title: "Laser Pointer Toy", weight: "1 pc", term: "cat laser toy" },
      { title: "Rubber Ball Toy", weight: "1 pc", term: "dog rubber ball" },
      { title: "Fleece Pet Blanket", weight: "1 pc", term: "pet blanket" },
      { title: "Pet Nail Clippers", weight: "1 pc", term: "pet nail clippers" },
    ],
    'cat-needs': [
      { title: "Whiskas Adult Dry Cat Food", weight: "1.2 kg", term: "cat food dry" },
      { title: "Whiskas Wet Cat Food", weight: "85 g", term: "cat food pouch" },
      { title: "Scoopable Cat Litter", weight: "5 kg", term: "cat litter" },
      { title: "Cat Scratching Post", weight: "1 pc", term: "cat scratcher" },
      { title: "Me-O Adult Cat Food", weight: "1.2 kg", term: "meo cat food" },
      { title: "Royal Canin Kitten Food", weight: "400 g", term: "kitten food" },
      { title: "Sheba Premium Cat Food", weight: "70 g", term: "sheba cat food" },
      { title: "Cat Litter Scoop", weight: "1 pc", term: "litter scoop" },
      { title: "Tofu Cat Litter", weight: "7 L", term: "tofu cat litter" },
      { title: "Drools Dry Cat Food", weight: "1.2 kg", term: "drools cat food" },
      { title: "Purepet Ocean Fish Adult Cat Food", weight: "1 kg", term: "purepet cat food" },
      { title: "Cat Collar with Bell", weight: "1 pc", term: "cat collar bell" },
      { title: "Deodorizing Litter Spray", weight: "250 ml", term: "cat litter spray" },
      { title: "Cat Tree Tower", weight: "1 pc", term: "cat tree" },
      { title: "Cat Grooming Brush", weight: "1 pc", term: "cat brush" },
      { title: "Kitten Milk Replacer", weight: "200 g", term: "kitten milk" },
      { title: "Catnip Leaves", weight: "10 g", term: "catnip" },
      { title: "Interactive Mouse Toy", weight: "1 pc", term: "cat mouse toy" },
      { title: "Anti-Tick Cat Shampoo", weight: "200 ml", term: "cat shampoo" },
      { title: "Cat Dental Treats", weight: "50 g", term: "cat dental treats" },
      { title: "Licking Mat for Cats", weight: "1 pc", term: "cat lick mat" },
      { title: "Covered Litter Box", weight: "1 pc", term: "covered cat litter box" },
      { title: "Grain Free Cat Food", weight: "1 kg", term: "grain free cat food" },
      { title: "Cat Grass Kit", weight: "1 pc", term: "cat grass" },
      { title: "Window Cat Hammock", weight: "1 pc", term: "cat window bed" },
    ],
    'diverse': [
      { title: "Bird Seed Mix", weight: "500 g", term: "bird food seed" },
      { title: "Fish Flakes", weight: "50 g", term: "fish food flakes" },
      { title: "Turtle Food Pellets", weight: "100 g", term: "turtle food" },
      { title: "Guinea Pig Pellets", weight: "1 kg", term: "guinea pig food" },
      { title: "Rabbit Food Mix", weight: "1 kg", term: "rabbit food" },
      { title: "Hamster Food", weight: "500 g", term: "hamster food" },
      { title: "Parrot Seed Blend", weight: "500 g", term: "parrot food" },
      { title: "Fish Tank Filter", weight: "1 pc", term: "aquarium filter" },
      { title: "Aquarium Water Conditioner", weight: "100 ml", term: "aquarium water conditioner" },
      { title: "Bird Cage Feeder", weight: "1 pc", term: "bird feeder" },
      { title: "Cuttlebone for Birds", weight: "2 pcs", term: "cuttlebone" },
      { title: "Small Animal Bedding", weight: "1 kg", term: "hamster bedding" },
      { title: "Alfalfa Hay", weight: "500 g", term: "alfalfa hay" },
      { title: "Timothy Hay", weight: "500 g", term: "timothy hay" },
      { title: "Hamster Wheel", weight: "1 pc", term: "hamster wheel" },
      { title: "Aquarium Air Pump", weight: "1 pc", term: "aquarium air pump" },
      { title: "Betta Fish Food", weight: "20 g", term: "betta fish food" },
      { title: "Bird Swing", weight: "1 pc", term: "bird toy swing" },
      { title: "Mineral Block for Birds", weight: "1 pc", term: "bird mineral block" },
      { title: "Fish Net", weight: "1 pc", term: "aquarium fish net" },
      { title: "Aquarium Heater", weight: "1 pc", term: "aquarium heater" },
      { title: "Small Animal Water Bottle", weight: "1 pc", term: "hamster water bottle" },
      { title: "Turtle Calcium Block", weight: "1 pc", term: "turtle calcium" },
      { title: "Goldfish Pellets", weight: "100 g", term: "goldfish food" },
      { title: "Ferret Food", weight: "1 kg", term: "ferret food" },
    ],
    'dog-needs': [
      { title: "Pedigree Adult Dry Dog Food", weight: "3 kg", term: "pedigree adult dog food" },
      { title: "Pedigree Puppy Dry Dog Food", weight: "3 kg", term: "pedigree puppy food" },
      { title: "Pedigree Adult Wet Dog Food", weight: "70 g", term: "pedigree wet dog food" },
      { title: "Drools Adult Wet Dog Food", weight: "150 g", term: "drools wet dog food" },
      { title: "Pedigree Wet Puppy Food", weight: "70 g", term: "pedigree wet puppy food" },
      { title: "Drools Focus Adult Dry", weight: "1.2 kg", term: "drools focus dog food" },
      { title: "Pedigree Meat Jerky", weight: "80 g", term: "pedigree meat jerky" },
      { title: "Drools Chicken & Liver Gravy", weight: "12 x 150 g", term: "drools gravy dog food" },
      { title: "HUFT Sara's Wholesome Grain-Free", weight: "400 g", term: "huft dog food" },
      { title: "Royal Canin Maxi Adult", weight: "4 kg", term: "royal canin dog food" },
      { title: "Chappi Adult Dry Dog Food", weight: "3 kg", term: "chappi dog food" },
      { title: "Goodies Dental Chews", weight: "125 g", term: "dog dental chews" },
      { title: "Dog Muzzle", weight: "1 pc", term: "dog muzzle" },
      { title: "Meat Up Biscuits", weight: "500 g", term: "dog biscuits" },
      { title: "Dog Chew Bones", weight: "5 pcs", term: "dog chew bones" },
      { title: "Puppy Teething Toys", weight: "1 pc", term: "puppy teething toy" },
      { title: "Dog Diapers (Large)", weight: "10 pcs", term: "dog diapers" },
      { title: "Joint Supplement for Dogs", weight: "60 tabs", term: "dog joint supplement" },
      { title: "Calming Treats for Dogs", weight: "100 g", term: "calming dog treats" },
      { title: "Dog Cooling Mat", weight: "1 pc", term: "dog cooling mat" },
      { title: "Dog Car Harness", weight: "1 pc", term: "dog car harness" },
      { title: "Bark Collar", weight: "1 pc", term: "bark collar" },
      { title: "Rawhide Free Chews", weight: "200 g", term: "rawhide free dog chews" },
      { title: "Dog Raincoat", weight: "1 pc", term: "dog raincoat" },
      { title: "Himalayan Cheese Chew", weight: "100 g", term: "yak cheese dog chew" },
    ],
    'pet-grooming': [
      { title: "Pet Shampoo with Conditioner", weight: "200 ml", term: "dog shampoo" },
      { title: "Tick & Flea Spray", weight: "100 ml", term: "tick spray dog" },
      { title: "Pet Wipes (Aloe Vera)", weight: "50 wipes", term: "pet wipes" },
      { title: "Slicker Pet Brush", weight: "1 pc", term: "pet brush" },
      { title: "Deshedding Tool", weight: "1 pc", term: "dog deshedding tool" },
      { title: "Waterless Pet Shampoo", weight: "150 ml", term: "waterless pet shampoo" },
      { title: "Tear Stain Remover", weight: "50 ml", term: "dog tear stain remover" },
      { title: "Pet Ear Cleaner", weight: "100 ml", term: "pet ear cleaner" },
      { title: "Paw Butter", weight: "50 g", term: "dog paw balm" },
      { title: "Double Sided Pin Brush", weight: "1 pc", term: "dog pin brush" },
      { title: "Pet Toothbrush & Paste", weight: "1 kit", term: "dog toothbrush" },
      { title: "Grooming Scissors Set", weight: "1 set", term: "pet grooming scissors" },
      { title: "Flea and Tick Shampoo", weight: "200 ml", term: "flea shampoo" },
      { title: "Oatmeal Dog Shampoo", weight: "200 ml", term: "oatmeal dog shampoo" },
      { title: "Pet Hair Roller", weight: "1 pc", term: "pet hair remover roller" },
      { title: "Cat Grooming Glove", weight: "1 pc", term: "pet grooming glove" },
      { title: "Matting Comb", weight: "1 pc", term: "dematting comb dog" },
      { title: "Pet Cologne", weight: "100 ml", term: "dog perfume" },
      { title: "Nail Trimmer with Guard", weight: "1 pc", term: "dog nail trimmer grinder" },
      { title: "Puppy Mild Shampoo", weight: "200 ml", term: "puppy tearless shampoo" },
      { title: "Anti-Dandruff Pet Spray", weight: "100 ml", term: "dog dandruff spray" },
      { title: "Grooming Wipes for Cats", weight: "50 wipes", term: "cat grooming wipes" },
      { title: "White Coat Brightening Shampoo", weight: "200 ml", term: "whitening dog shampoo" },
      { title: "Styptic Powder", weight: "15 g", term: "pet styptic powder" },
      { title: "Knothole Detangler Spray", weight: "100 ml", term: "dog detangler spray" },
    ]
  };

  let ptId = 1;
  const exportData = {};

  categories.forEach(cat => {
    exportData[cat] = [];
    templates[cat].forEach(tmpl => {
      exportData[cat].push({
        id: \`pt\${ptId++}\`,
        title: tmpl.title,
        weight: tmpl.weight,
        price: 150,
        originalPrice: 180,
        discount: "16%",
        searchTerm: tmpl.term,
      });
    });
  });

  const obj = "export const PET_PRODUCTS_BY_CATEGORY = " + JSON.stringify(exportData, null, 2) + ";";
  fs.writeFileSync('pet_data_temp.js', obj);
  console.log('SUCCESS');
} catch (e) {
  fs.writeFileSync('error.log', e.stack);
}
