// grocery_data_loc.jsx will be generated by this script
const fs = require("fs");
const path = require("path");
const https = require("https");
const http = require("http");
const google = require("googlethis");

const categories = [
  "fresh-vegetables",
  "fresh-fruits",
  "exotics",
  "seasonal",
  "trusted-organic",
];

const templates = {
  "fresh-vegetables": [
    { title: "Coriander Bunch", term: "Coriander leaves bunch" },
    { title: "Onion", term: "Red Onion" },
    { title: "Green Chilli", term: "Green Chilli" },
    { title: "Ooty Carrot", term: "Ooty Carrot" },
    { title: "Potato", term: "Potato" },
    { title: "Lemon", term: "Raw Lemon" },
    { title: "Ginger", term: "Ginger root" },
    { title: "Hybrid Tomato", term: "Tomato" },
    { title: "Mint Leaves", term: "Mint Leaves bunch" },
    { title: "Curry Leaves", term: "Curry Leaves" },
    { title: "Green Capsicum", term: "Green Capsicum" },
    { title: "Green Cucumber", term: "Green Cucumber" },
    { title: "Cabbage", term: "Cabbage" },
    { title: "Cauliflower", term: "Cauliflower" },
    { title: "Brinjal", term: "Purple Brinjal" },
    { title: "Spinach", term: "Spinach bunch palak" },
    { title: "Bitter Gourd", term: "Bitter Gourd" },
    { title: "Bottle Gourd", term: "Bottle Gourd" },
    { title: "Drumstick", term: "Drumstick vegetable" },
    { title: "Snake Gourd", term: "Snake Gourd" },
    { title: "Ridge Gourd", term: "Ridge Gourd" },
    { title: "Ash Gourd", term: "Ash Gourd vegetable" },
    { title: "Broad Beans", term: "Broad Beans vegetable" },
    { title: "Cluster Beans", term: "Cluster Beans" },
    { title: "Plantain Stem", term: "Plantain Stem vegetable" },
    { title: "Sweet Potato", term: "Sweet Potato" },
    { title: "Yam", term: "Yam vegetable" },
    { title: "Taro Root", term: "Taro Root" },
    { title: "Radish", term: "White Radish" },
    { title: "Turnip", term: "Turnip vegetable" },
    { title: "Beetroot", term: "Beetroot" },
    { title: "Spring Onion", term: "Spring Onion" },
    { title: "Leeks", term: "Leeks vegetable" },
    { title: "Banana Flower", term: "Banana Flower vegetable" },
    { title: "Ivy Gourd", term: "Ivy Gourd Tindora" },
  ],
  "fresh-fruits": [
    { title: "Apple", term: "Red Apple Fruit" },
    { title: "Banana (Robusta)", term: "Robusta Banana" },
    { title: "Papaya", term: "Ripe Papaya" },
    { title: "Pomegranate", term: "Pomegranate fruit" },
    { title: "Watermelon", term: "Watermelon whole" },
    { title: "Orange", term: "Orange Fruit" },
    { title: "Green Grapes", term: "Green Grapes" },
    { title: "Pineapple", term: "Pineapple" },
    { title: "Sweet Lime", term: "Sweet Lime Mosambi" },
    { title: "Guava", term: "Guava fruit" },
    { title: "Sapota", term: "Sapota Chikoo fruit" },
    { title: "Black Grapes", term: "Black Grapes" },
    { title: "Apple (Royal Gala)", term: "Royal Gala Apple" },
    { title: "Banana (Yelakki)", term: "Yelakki Banana" },
    { title: "Banana (Red)", term: "Red Banana" },
    { title: "Muskmelon", term: "Muskmelon" },
    { title: "Pear", term: "Pear fruit" },
    { title: "Dates", term: "Kimia Dates" },
    { title: "Tender Coconut", term: "Tender Coconut" },
    { title: "Jackfruit", term: "Jackfruit pieces" },
    { title: "Fig", term: "Fresh Fig fruit" },
    { title: "Amla", term: "Amla Indian Gooseberry" },
    { title: "Apple (Fuji)", term: "Fuji Apple" },
    { title: "Apple (Green)", term: "Green Apple" },
    { title: "Grapefruit", term: "Grapefruit" },
    { title: "Red Apple (Washington)", term: "Washington Red Apple" },
    { title: "Strawberry", term: "Fresh Strawberry" },
    { title: "Plums", term: "Plum fruit" },
    { title: "Melon (Kharbuja)", term: "Kharbuja Melon" },
    { title: "Cranberries", term: "Fresh Cranberries" },
    { title: "Raspberries", term: "Fresh Raspberries" },
    { title: "Blackberries", term: "Fresh Blackberries" },
    { title: "Gooseberry", term: "Gooseberry Nellikai" },
    { title: "Peach", term: "Peach fruit" },
    { title: "Kiwi (Gold)", term: "Gold Kiwi fruit" },
  ],
  exotics: [
    { title: "Avocado", term: "Avocado Hass" },
    { title: "Dragon Fruit", term: "Dragon Fruit pink" },
    { title: "Kiwi", term: "Green Kiwi fruit" },
    { title: "Blueberries", term: "Fresh Blueberries" },
    { title: "Broccoli", term: "Fresh Broccoli" },
    { title: "Zucchini", term: "Green Zucchini" },
    { title: "Cherry Tomatoes", term: "Red Cherry Tomatoes" },
    { title: "Asparagus", term: "Green Asparagus" },
    { title: "Red Bell Pepper", term: "Red Capsicum Bell Pepper" },
    { title: "Yellow Bell Pepper", term: "Yellow Capsicum Bell Pepper" },
    { title: "Celery", term: "Celery sticks" },
    { title: "Parsley", term: "Parsley leaves" },
    { title: "Italian Basil", term: "Italian Basil leaves" },
    { title: "Lemongrass", term: "Lemongrass stalks" },
    { title: "Galangal", term: "Galangal root" },
    { title: "Kaffir Lime Leaves", term: "Kaffir Lime Leaves" },
    { title: "Bok Choy", term: "Bok Choy vegetable" },
    { title: "Mangosteen", term: "Mangosteen fruit" },
    { title: "Rambutan", term: "Rambutan fruit" },
    { title: "Passion Fruit", term: "Passion Fruit" },
    { title: "Star Fruit", term: "Star Fruit Carambola" },
    { title: "Grapefruit (Ruby Red)", term: "Ruby Red Grapefruit" },
    { title: "Baby Corn", term: "Baby Corn" },
    { title: "Snow Peas", term: "Snow Peas" },
    { title: "Button Mushrooms", term: "White Button Mushrooms" },
    { title: "Oyster Mushrooms", term: "Oyster Mushrooms" },
    { title: "Shiitake Mushrooms", term: "Shiitake Mushrooms" },
    { title: "Red Cabbage", term: "Red Cabbage" },
    { title: "Iceberg Lettuce", term: "Iceberg Lettuce head" },
    { title: "Romaine Lettuce", term: "Romaine Lettuce" },
    { title: "Lollo Rosso", term: "Lollo Rosso Lettuce" },
    { title: "Thai Basil", term: "Thai Basil leaves" },
    { title: "Bird's Eye Chilli", term: "Bird's Eye Chilli" },
    { title: "Zucchini (Yellow)", term: "Yellow Zucchini" },
    { title: "Sugar Snap Peas", term: "Sugar Snap Peas" },
  ],
  seasonal: [
    { title: "Mango (Alphonso)", term: "Alphonso Mango" },
    { title: "Mango (Banganapalli)", term: "Banganapalli Mango" },
    { title: "Mango (Totapuri)", term: "Totapuri Mango" },
    { title: "Lychee", term: "Lychee fruit" },
    { title: "Cherries", term: "Fresh Red Cherries" },
    { title: "Plums (Indian)", term: "Indian Plum fruit" },
    { title: "Peaches (Indian)", term: "Indian Peach fruit" },
    { title: "Custard Apple", term: "Custard Apple Sitaphal" },
    { title: "Guava (Pink)", term: "Pink Guava" },
    { title: "Watermelon (Kiran)", term: "Kiran Watermelon" },
    { title: "Sweet Corn", term: "Sweet Corn cob" },
    { title: "Green Peas (Mutter)", term: "Green Peas Mutter" },
    { title: "Carrot (Delhi/Red)", term: "Red Carrot Delhi" },
    { title: "Radish (Red)", term: "Red Radish" },
    { title: "Turnip (White)", term: "White Turnip" },
    { title: "Amla (Desi)", term: "Desi Amla" },
    { title: "Jamun", term: "Jamun fruit" },
    { title: "Karonda", term: "Karonda fruit" },
    { title: "Phalsa", term: "Phalsa fruit" },
    { title: "Tamarind (Raw)", term: "Raw Tamarind" },
    { title: "Mango (Raw/Kacchi Kairi)", term: "Raw Mango Kacchi Kairi" },
    { title: "Singhara (Water Chestnut)", term: "Water Chestnut Singhara" },
    { title: "Sweet Potato (Shakarkandi)", term: "Sweet Potato Shakarkandi" },
    { title: "Yam (Suran/Elephant Foot)", term: "Elephant Foot Yam Suran" },
    { title: "Taro Root (Arbi)", term: "Arbi Taro Root" },
    { title: "Lotus Stem (Kamal Kakdi)", term: "Kamal Kakdi Lotus Stem" },
    { title: "Jackfruit (Raw)", term: "Raw Jackfruit" },
    { title: "Pineapple (Queen/Mauritius)", term: "Queen Pineapple" },
    { title: "Strawberry (Mahabaleshwar)", term: "Mahabaleshwar Strawberry" },
    { title: "Fig (Pune)", term: "Pune Fig" },
    { title: "Grapes (Nashik Black)", term: "Nashik Black Grapes" },
    { title: "Grapes (Nashik Green)", term: "Nashik Green Grapes" },
    { title: "Orange (Nagpur)", term: "Nagpur Orange" },
    { title: "Kinnow", term: "Kinnow Orange" },
    { title: "Sweet Lime (Malta)", term: "Malta Sweet Lime" },
  ],
  "trusted-organic": [
    { title: "Organic Tomato", term: "Organic Tomato" },
    { title: "Organic Onion", term: "Organic Red Onion" },
    { title: "Organic Potato", term: "Organic Potato" },
    { title: "Organic Carrot", term: "Organic Carrot" },
    { title: "Organic Cucumber", term: "Organic Cucumber" },
    { title: "Organic Spinach", term: "Organic Spinach bunch" },
    { title: "Organic Coriander", term: "Organic Coriander leaves" },
    { title: "Organic Mint", term: "Organic Mint leaves" },
    { title: "Organic Green Chilli", term: "Organic Green Chilli" },
    { title: "Organic Ginger", term: "Organic Ginger root" },
    { title: "Organic Garlic", term: "Organic Garlic bulbs" },
    { title: "Organic Lemon", term: "Organic Lemon" },
    { title: "Organic Apple", term: "Organic Apple fruit" },
    { title: "Organic Banana", term: "Organic Banana" },
    { title: "Organic Papaya", term: "Organic Ripe Papaya" },
    { title: "Organic Mango", term: "Organic Mango" },
    { title: "Organic Pomegranate", term: "Organic Pomegranate" },
    { title: "Organic Orange", term: "Organic Orange fruit" },
    { title: "Organic Guava", term: "Organic Guava" },
    { title: "Organic Sweet Lime", term: "Organic Sweet Lime" },
    { title: "Organic Grapes", term: "Organic Grapes" },
    { title: "Organic Watermelon", term: "Organic Watermelon" },
    { title: "Organic Tur Dal", term: "Organic Tur Dal" },
    { title: "Organic Moong Dal", term: "Organic Moong Dal" },
    { title: "Organic Urad Dal", term: "Organic Urad Dal" },
    { title: "Organic Chana Dal", term: "Organic Chana Dal" },
    { title: "Organic Basmati Rice", term: "Organic Basmati Rice" },
    { title: "Organic Sona Masoori Rice", term: "Organic Sona Masoori Rice" },
    { title: "Organic Brown Rice", term: "Organic Brown Rice" },
    { title: "Organic Wheat Atta", term: "Organic Wheat Atta" },
    { title: "Organic Besan", term: "Organic Besan" },
    { title: "Organic Sugar", term: "Organic Sugar" },
    { title: "Organic Jaggery", term: "Organic Jaggery" },
    { title: "Organic Honey", term: "Organic Honey bottle" },
    { title: "Organic Ghee", term: "Organic Cow Ghee" },
  ],
};

const downloadImg = (url, filepath, redirects = 0) => {
  return new Promise((resolve) => {
    if (redirects > 3) return resolve(false);

    let timeout = setTimeout(() => resolve(false), 5000);
    const client = url.startsWith("https") ? https : http;
    const req = client.get(
      url,
      { headers: { "User-Agent": "Mozilla/5.0" } },
      (res) => {
        clearTimeout(timeout);
        if (
          res.statusCode >= 300 &&
          res.statusCode < 400 &&
          res.headers.location
        ) {
          let newUrl = res.headers.location;
          if (!newUrl.startsWith("http")) {
            const urlObj = new URL(url);
            newUrl = `${urlObj.protocol}//${urlObj.host}${newUrl}`;
          }
          return downloadImg(newUrl, filepath, redirects + 1).then(resolve);
        }

        if (res.statusCode === 200) {
          const contentType = res.headers["content-type"];
          if (!contentType || !contentType.startsWith("image/"))
            return resolve(false);

          const fileStream = fs.createWriteStream(filepath);
          res
            .pipe(fileStream)
            .on("finish", () => resolve(true))
            .on("error", () => resolve(false));
        } else {
          resolve(false);
        }
      },
    );

    req.on("error", () => {
      clearTimeout(timeout);
      resolve(false);
    });
    req.on("timeout", () => {
      req.destroy();
      clearTimeout(timeout);
      resolve(false);
    });
  });
};

const ASSET_DIR = path.join(__dirname, "assets", "grocery");
if (!fs.existsSync(ASSET_DIR)) {
  fs.mkdirSync(ASSET_DIR, { recursive: true });
}

fs.readdirSync(ASSET_DIR).forEach((f) =>
  fs.unlinkSync(path.join(ASSET_DIR, f)),
);

async function generateActualImages() {
  const finalCategories = {
    "fresh-vegetables": [],
    "fresh-fruits": [],
    exotics: [],
    seasonal: [],
    "trusted-organic": [],
  };

  for (const cat of categories) {
    let validCount = 0;
    let ptId = 1;
    let templateIdx = 0;
    const categoryTemplates = templates[cat];

    while (validCount < 25) {
      const tmpl = categoryTemplates[templateIdx % categoryTemplates.length];
      const filename = `${cat}_${ptId}.jpg`;
      const filepath = path.join(ASSET_DIR, filename);

      const query = tmpl.term + " raw fresh white background high quality";
      console.log(`Searching for [${validCount + 1}/25] in ${cat}... ${query}`);

      try {
        const images = await google.image(query, { safe: false });
        let downloaded = false;

        const tries = Math.min(5, images.length);
        for (let i = 0; i < tries; i++) {
          const imgUrl = images[i].url;
          if (!imgUrl) continue;

          try {
            const success = await downloadImg(imgUrl, filepath);
            if (success) {
              const stats = fs.statSync(filepath);
              // Image must be > 15KB to be considered a real product image usually
              if (stats.size > 15000) {
                downloaded = true;
                break;
              } else {
                fs.unlinkSync(filepath);
              }
            }
          } catch (e) {
            if (fs.existsSync(filepath)) fs.unlinkSync(filepath);
          }
        }

        if (downloaded) {
          finalCategories[cat].push({
            id: `${cat}_${ptId}`,
            title: tmpl.title,
            weight: "500 g", // Default weight
            price: Math.floor(Math.random() * 80) + 20,
            originalPrice: Math.floor(Math.random() * 80) + 120,
            discount: Math.floor(Math.random() * 20) + 5 + "%",
            searchTerm: tmpl.term,
            imageFile: filename,
            imagePath: `./assets/grocery/${filename}`,
          });
          validCount++;
          ptId++;
          console.log(`✅ Kept: ${tmpl.term} (${validCount}/25)`);
        } else {
          console.log(`❌ Dropped (No valid image): ${tmpl.term}`);
        }
      } catch (err) {
        console.log(`❌ Dropped (API err): ${tmpl.term}`);
      }

      templateIdx++;
    }
  }

  console.log(`Finished downloading Grocery images!`);

  let outputStr = "";
  for (const cat in finalCategories) {
    finalCategories[cat].forEach((p) => {
      outputStr += `import img_${p.id.replace(/-/g, "_")} from '${p.imagePath}';\n`;
    });
  }

  outputStr += "\nexport const GROCERY_PRODUCTS_BY_CATEGORY = {\n";
  for (const cat in finalCategories) {
    const products = finalCategories[cat];
    outputStr += `  "${cat}": [\n`;
    for (const p of products) {
      outputStr += `    {
      "id": "${p.id}",
      "title": "${p.title}",
      "weight": "${p.weight}",
      "price": ${p.price},
      "originalPrice": ${p.originalPrice},
      "discount": "${p.discount}",
      "searchTerm": "${p.searchTerm}",
      "image": img_${p.id.replace(/-/g, "_")}
    },\n`;
    }
    outputStr += `  ],\n`;
  }
  outputStr += "};\n";

  fs.writeFileSync(
    path.join(__dirname, "grocery_data_loc.jsx"),
    outputStr,
    "utf8",
  );
  console.log("Rewrote grocery_data_loc.jsx with 25 items per category.");
}

generateActualImages();
